### ISSUE TITLE
Website has no valid SSL certificate

### ISSUE THREAD

**Issue by Jelenkee** [alacritty/website#20]
![image](https://github.com/alacritty/website/assets/59470612/b4dd75a7-34d2-483a-b062-c3fd362dbf2c)

I assume because of the new year :wink:

**Comment by kchibisov** [comment]
We'll have to wait for @chrisduerr for it to get sorted, probably the job to renew failed.

**Comment by kchibisov** [comment]
Strange that it still works fine if I go to in firefox, even after reloads/restarts...

**Comment by chrisduerr** [comment]
![tmp](https://github.com/alacritty/website/assets/8886672/378369c0-59f2-4a6f-9282-ac3e75fc3024)

Issuing with Let's Encrypt is in intervals disconnected from new year's and works just fine for me in Firefox. I'm not sure if it ever worked with wget/curl, maybe they're struggling with elliptic curves?

**Comment by chrisduerr** [comment]
Turns out I accidentally used the cert.pem instead of fullchain.pem when setting up the server again after Debian nuked itself during the last update. Should work again now.
