### ISSUE TITLE
New website design

### ISSUE THREAD

**Issue by iDuuck** [alacritty/website#8]
Hello guys, I am a developer at Fintory, and I recently stumbled across Alacritty, and think it's awesome to have such a Terminal client.

When checking your homepage, I saw that it is a little "outdated" when it comes to the overall design. I thought to give it a quick spin, and fiddled around a little.

Please lmk what you think about this:

![alacritty-web](https://user-images.githubusercontent.com/325241/175507855-c3ec181f-a363-4984-bd7b-3c16a8b9e853.png)

**Comment by chrisduerr** [comment]
I have no doubt there could be many improvements made to Alacritty's website, but I much prefer the current design over your mockup. If you have more precise incremental suggestions, feel free to open separate issues, but I think redesigning the website every couple months on a whim is just a waste of time.
